<?php

namespace Dotlines\GhooriOnDemand\Tests;

use Dotlines\GhooriOnDemand\Models\WebhookResponse;
use PHPUnit\Framework\TestCase;

class WebhookResponseTest extends TestCase
{
    public string $message;
    final public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->message = "ddsd";
    }

    /**
     * @test
     */
    final public function it_can_construct_a_webhookResponse(): void
    {
        $webhookResponseObj = new WebhookResponse($this->message);
        self::assertEquals("Dotlines\GhooriOnDemand\Models\WebhookResponse", get_class($webhookResponseObj));
    }

    /**
     * @test
     * @throws \JsonException
     */
    final public function checks_if_message_is_a_string(): void
    {
        $webhookResponseObj = new WebhookResponse($this->message);
        $response = $webhookResponseObj->__toString();
        $response = json_decode($response, true);
        self::assertArrayHasKey('actionTaken', $response, json_encode($response));
    }
}
