<?php

namespace Dotlines\GhooriOnDemand\Tests;

use Dotlines\GhooriOnDemand\Models\WebhookResponse;
use PHPUnit\Framework\TestCase;

class WebhookResponseTest extends TestCase
{
    public string $message;
    public final function  setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->message = "ddsd";
    }

    /**
     * @test
     */
    final public function it_can_construct_a_webhookResponse_object(): void
    {
        $webhookResponseObj = new WebhookResponse($this->message);
        self::assertEquals("Dotlines\GhooriOnDemand\Models\WebhookResponse", get_class($webhookResponseObj));
    }

    /**
     * @test
     * @throws \JsonException
     */
    final public function it_can_return_json_encoded_parameter_of_webhookResponse_object(): void
    {
        $webhookResponseObj = new WebhookResponse($this->message);
        $responseResult = json_decode($webhookResponseObj->__toString());
        self::assertObjectHasAttribute("actionTaken", $responseResult);
        self::assertNotEmpty($responseResult);
        self::assertNotEmpty("actionTaken", $responseResult->actionTaken);
    }
}
